name: Build and StreamAnalytics CI/CD

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.18'

      - name: Install Azure Stream Analytics CLI
        run: npm install -g -f azure-streamanalytics-cicd --loglevel verbose

      - name: Build ASA Project
        run: |
          azure-streamanalytics-cicd build  --project stream-analytics/SampleJob.asaproj --outputPath ./Deploy

   

