name: Build and StreamAnalytics CI/CD

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest  # Equivalent to pool: vmImage: windows-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Install Node.js
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.18'

    # Install Azure Stream Analytics CLI
    - name: Install Azure Stream Analytics CLI
      run: npm install -g azure-streamanalytics-cicd --f --loglevel verbose

    # Run the Stream Analytics Build
    - name: Run Stream Analytics Build
      run: |
        azure-streamanalytics-cicd build -project <project.asaproj> -outputpath <path_to_output>
