name: Build ASA Project on Windows with Manual CLI Install

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.18'

      - name: Download .NET Core 3.1 Runtime
        run: |
         curl.exe -L "https://dotnetcli.azureedge.net/dotnet/Runtime/3.1.32/dotnet-runtime-3.1.32-win-x64.exe" -o "C:\dotnet-runtime-3.1.exe"
         Start-Process "C:\dotnet-runtime-3.1.exe" -ArgumentList "/quiet","/norestart" -Wait



      - name: Install ASA CLI manually
        run: |
          mkdir C:\asa-cli
          curl.exe -L "https://registry.npmjs.org/azure-streamanalytics-cicd/-/azure-streamanalytics-cicd-3.0.0.tgz" -o C:\asa-cli\cli.tgz
          tar -xvzf C:\asa-cli\cli.tgz -C C:\asa-cli
          cd C:\asa-cli\package
          npm install
          npm link
          echo "$env:APPDATA\npm" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8

      - name: Build Stream Analytics Project
        run: azure-streamanalytics-cicd build --v2 --project ./stream-analytics/SampleJob.asaproj.json --outputPath ./Deploy



      
