name: Install BizTalk Build Component

on: [push, pull_request]


jobs:
  download-biztalk-build-component:
    runs-on: windows-2019
    steps:
      - name: Set up repository
        uses: actions/checkout@v4

      - name: Download BizTalk Build Component Setup
        run: |
          $downloadUrl = "https://aka.ms/TestBuildComponentSetup.EN.zip"
          $outputPath = "C:\\BizTalkBuildComponentSetup.exe"
          Invoke-WebRequest -Uri $downloadUrl -OutFile $outputPath
        shell: pwsh
