name: Install Cargo Outdated

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Install cargo-outdated
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl-dev pkg-config
        cargo install cargo-outdated

    - name: Verify installation
      run: cargo outdated --version
