name: Download and Install MySQL

on: [push, pull_request]
jobs:
  download-and-verify:
    runs-on: windows-2022

    steps:
      - name: Set up PowerShell
        uses: actions/setup-powershell@v2

      - name: Download MySQL Package
        run: |
          Invoke-WebRequest `
            -Uri "https://cdn.mysql.com/Downloads/MySQL-8.0/mysql-8.0.42-winx64.msi" `
            -OutFile "mysql-8.0.42-winx64.msi"

      - name: Compute SHA-256 Hash
        id: compute-hash
        run: |
          $filePath = "mysql-8.0.42-winx64.msi"
          $sha256 = Get-FileHash -Path $filePath -Algorithm SHA256
          Write-Output "SHA256: $($sha256.Hash)"
          echo "::set-output name=sha256::$($sha256.Hash)"

      - name: Print SHA-256 Hash
        run: |
          echo "SHA-256 Hash: ${{ steps.compute-hash.outputs.sha256 }}"

