name: Install Podman and Container Networking Plugins

on: [push, pull_request]

jobs:
  setup-podman:
    name: Setup Podman and Plugins
    runs-on: ubuntu-22.04

    steps:
      # Checkout the repository (if needed)
      - name: Checkout Code
        uses: actions/checkout@v3

      # Update packages and install Podman
      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      # Verify Podman installation
      - name: Verify Podman Installation
        run: podman --version

      # Install container networking plugins
      - name: Install Container Networking Plugins
        run: |
          sudo apt-get install -y containernetworking-plugins

      # Verify container networking plugins installation
      - name: Verify Container Networking Plugins
        run: |
          ls /usr/lib/cni/

      - name: Remove Podman Network
        run: |
          podman network rm test-net
          podman network ls
