name: Install Podman and Configure Network Plugins

on: [push, pull_request]

jobs:
  setup-podman:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4



      - name: Install Podman
        run: |
          sudo apt-get install -y podman



      - name: Create Podman network
        run: |
          podman network create -d bridge test-net
          podman network ls
