name: Ubuntu 22.04 Workflow

on: [push, pull_request]

jobs:
  ubuntu-22-job:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run a sample script
      run: |
        echo "Running on Ubuntu 22.04"
        uname -a
       

