name: Install PowerShell Az Modules

on:
  on: [push, pull_request]

jobs:
  install-azmodules:
    runs-on: ubuntu-24.04 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install PowerShell
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https software-properties-common
          wget -q "https://packages.microsoft.com/config/ubuntu/24.04/packages-microsoft-prod.deb"
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y powershell
          pwsh --version

      - name: Run Install-PowerShellAzModules.ps1
        env:
          HELPER_SCRIPTS: ${{ github.workspace }}/scripts
        run: |
          pwsh -File ${{ github.workspace }}/Install-PowerShellAzModules.ps1
