name: Install PowerShell Az Modules

on:
  push:
    paths:
      - 'images/ubuntu/scripts/build/Install-PowerShellAzModules.ps1'
  pull_request:
    paths:
      - 'images/ubuntu/scripts/build/Install-PowerShellAzModules.ps1'

jobs:
  install-az-modules:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PowerShell
        uses: actions/setup-powershell@v2

      - name: Run Install-PowerShellAzModules.ps1
        shell: pwsh
        run: |
          pwsh images/ubuntu/scripts/build/Install-PowerShellAzModules.ps1
