name: My Workflow
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Microsoft Repos
        run: |
          sudo chmod +x ./images/ubuntu/scripts/build/install-ms-repos.sh
          sudo ./images/ubuntu/scripts/build/install-ms-repos.sh
